// *** AUTOMATICALLY GENERATED  ***
// *** EDITS MAY BE OVERWRITTEN ***
// Download CSV file from IANA: https://www.iana.org/assignments/uri-schemes/uri-schemes.xml


#include "urischemes.h"


uri_schemes_t uri_scheme_table[] = {
	//Scheme                                 Description                            Reference
	{"aaa",                                 "Diameter Protocol",                   "[RFC6733]"},
	{"aaas",                                "Diameter Protocol with Secure Tran",  "[RFC6733]"},
	{"about",                               "about",                               "[RFC6694]"},
	{"acap",                                "application configuration access p",  "[RFC2244]"},
	{"acct",                                "acct",                                "[RFC7565]"},
	{"acd",                                 "acd",                                 "[Michael_Hedenus]"},
	{"acr",                                 "acr",                                 "[OMA-OMNA]"},
	{"adiumxtra",                           "adiumxtra",                           "[Dave_Thaler]"},
	{"adt",                                 "adt",                                 "[SAP_SE]"},
	{"afp",                                 "afp",                                 "[Dave_Thaler]"},
	{"afs",                                 "Andrew File System global file nam",  "[RFC1738]"},
	{"aim",                                 "aim",                                 "[Dave_Thaler]"},
	{"amss",                                "amss",                                "[RadioDNS_Project]"},
	{"android",                             "android",                             "[Adam_Barth][https://developer.and"},
	{"appdata",                             "appdata",                             "[urischemeowners_at_microsoft.com]"},
	{"apt",                                 "apt",                                 "[Dave_Thaler]"},
	{"ark",                                 "ark",                                 "[ARK_agency][https://n2t.net/ark:/"},
	{"attachment",                          "attachment",                          "[Dave_Thaler]"},
	{"aw",                                  "aw",                                  "[Dave_Thaler]"},
	{"barion",                              "barion",                              "[Bíró_Tamás]"},
	{"beshare",                             "beshare",                             "[Dave_Thaler]"},
	{"bitcoin",                             "bitcoin",                             "[Dave_Thaler]"},
	{"bitcoincash",                         "bitcoincash",                         "[Corentin_Mercier]"},
	{"blob",                                "blob",                                "[W3C_WebApps_Working_Group][Chris_"},
	{"bolo",                                "bolo",                                "[Dave_Thaler]"},
	{"browserext",                          "browserext",                          "[Mike_Pietraszak]"},
	{"calculator",                          "calculator",                          "[urischemeowners_at_microsoft.com]"},
	{"callto",                              "callto",                              "[Alexey_Melnikov]"},
	{"cap",                                 "Calendar Access Protocol",            "[RFC4324]"},
	{"cast",                                "cast",                                "[Adam_Barth][https://developers.go"},
	{"casts",                               "casts",                               "[Adam_Barth][https://developers.go"},
	{"chrome",                              "chrome",                              "[Dave_Thaler]"},
	{"chrome-extension",                    "chrome-extension",                    "[Dave_Thaler]"},
	{"cid",                                 "content identifier",                  "[RFC2392]"},
	{"coap",                                "coap",                                "[RFC7252]"},
	{"coap+tcp",                            "coap+tcp [1]",                        "[RFC8323]"},
	{"coap+ws",                             "coap+ws [1]",                         "[RFC8323]"},
	{"coaps",                               "coaps",                               "[RFC7252]"},
	{"coaps+tcp",                           "coaps+tcp [1]",                       "[RFC8323]"},
	{"coaps+ws",                            "coaps+ws [1]",                        "[RFC8323]"},
	{"com-eventbrite-attendee",             "com-eventbrite-attendee",             "[Bob_Van_Zant]"},
	{"content",                             "content",                             "[Dave_Thaler]"},
	{"conti",                               "conti",                               "[Michael_Hedenus]"},
	{"crid",                                "TV-Anytime Content Reference Ident",  "[RFC4078]"},
	{"cvs",                                 "cvs",                                 "[Dave_Thaler]"},
	{"dab",                                 "dab",                                 "[RadioDNS_Project]"},
	{"data",                                "data",                                "[RFC2397]"},
	{"dav",                                 "dav",                                 "[RFC4918]"},
	{"diaspora",                            "diaspora",                            "[Dennis_Schubert]"},
	{"dict",                                "dictionary service protocol",         "[RFC2229]"},
	{"did",                                 "did",                                 "[W3C_Credentials_Community_Group]["},
	{"dis",                                 "dis",                                 "[Christophe_Meessen]"},
	{"dlna-playcontainer",                  "dlna-playcontainer",                  "[DLNA]"},
	{"dlna-playsingle",                     "dlna-playsingle",                     "[DLNA]"},
	{"dns",                                 "Domain Name System",                  "[RFC4501]"},
	{"dntp",                                "dntp",                                "[Hans-Dieter_A._Hiep]"},
	{"dpp",                                 "dpp",                                 "[Gaurav_Jain][Wi-Fi_Alliance]"},
	{"drm",                                 "drm",                                 "[RadioDNS_Project]"},
	{"drop",                                "drop",                                "[Tim_McSweeney]"},
	{"dtn",                                 "DTNRG research and development",      "[RFC5050]"},
	{"dvb",                                 "dvb",                                 "[draft-mcroberts-uri-dvb]"},
	{"ed2k",                                "ed2k",                                "[Dave_Thaler]"},
	{"elsi",                                "elsi",                                "[Kimmo_Lindholm]"},
	{"example",                             "example",                             "[RFC7595]"},
	{"facetime",                            "facetime",                            "[Dave_Thaler]"},
	{"fax",                                 "fax",                                 "[RFC2806][RFC3966]"},
	{"feed",                                "feed",                                "[Dave_Thaler]"},
	{"feedready",                           "feedready",                           "[Mirko_Nosenzo]"},
	{"file",                                "Host-specific file names",            "[RFC8089]"},
	{"filesystem",                          "filesystem",                          "[W3C_WebApps_Working_Group][Chris_"},
	{"finger",                              "finger",                              "[Dave_Thaler]"},
	{"first-run-pen-experience",            "first-run-pen-experience",            "[urischemeowners_at_microsoft.com]"},
	{"fish",                                "fish",                                "[Dave_Thaler]"},
	{"fm",                                  "fm",                                  "[RadioDNS_Project]"},
	{"ftp",                                 "File Transfer Protocol",              "[RFC1738]"},
	{"fuchsia-pkg",                         "fuchsia-pkg",                         "[Adam_Barth][https://fuchsia.googl"},
	{"geo",                                 "Geographic Locations",                "[RFC5870]"},
	{"gg",                                  "gg",                                  "[Dave_Thaler]"},
	{"git",                                 "git",                                 "[Dave_Thaler]"},
	{"gizmoproject",                        "gizmoproject",                        "[Dave_Thaler]"},
	{"go",                                  "go",                                  "[RFC3368]"},
	{"gopher",                              "The Gopher Protocol",                 "[RFC4266]"},
	{"graph",                               "graph",                               "[Alastair_Green]"},
	{"gtalk",                               "gtalk",                               "[Dave_Thaler]"},
	{"h323",                                "H.323",                               "[RFC3508]"},
	{"ham",                                 "ham",                                 "[RFC7046]"},
	{"hcap",                                "hcap",                                "[urischemeowners_at_microsoft.com]"},
	{"hcp",                                 "hcp",                                 "[Alexey_Melnikov]"},
	{"http",                                "Hypertext Transfer Protocol",         "[RFC8615]"},
	{"https",                               "Hypertext Transfer Protocol Secure",  "[RFC8615]"},
	{"hxxp",                                "hxxp",                                "[draft-salgado-hxxp]"},
	{"hxxps",                               "hxxps",                               "[draft-salgado-hxxp]"},
	{"hydrazone",                           "hydrazone",                           "[Matthias_Merkel][https://tech.hyd"},
	{"iax",                                 "Inter-Asterisk eXchange Version 2",   "[RFC5456]"},
	{"icap",                                "Internet Content Adaptation Protoc",  "[RFC3507]"},
	{"icon",                                "icon",                                "[draft-lafayette-icon-uri-scheme]"},
	{"im",                                  "Instant Messaging",                   "[RFC3860]"},
	{"imap",                                "internet message access protocol",    "[RFC5092]"},
	{"info",                                "Information Assets with Identifier",  "[RFC4452]"},
	{"iotdisco",                            "iotdisco",                            "[Peter_Waher][http://www.iana.org/"},
	{"ipn",                                 "ipn",                                 "[RFC6260]"},
	{"ipp",                                 "Internet Printing Protocol",          "[RFC3510]"},
	{"ipps",                                "Internet Printing Protocol over HT",  "[RFC7472]"},
	{"irc",                                 "irc",                                 "[Dave_Thaler]"},
	{"irc6",                                "irc6",                                "[Dave_Thaler]"},
	{"ircs",                                "ircs",                                "[Dave_Thaler]"},
	{"iris",                                "Internet Registry Information Serv",  "[RFC3981]"},
	{"iris.beep",                           "iris.beep",                           "[RFC3983]"},
	{"iris.lwz",                            "iris.lwz",                            "[RFC4993]"},
	{"iris.xpc",                            "iris.xpc",                            "[RFC4992]"},
	{"iris.xpcs",                           "iris.xpcs",                           "[RFC4992]"},
	{"isostore",                            "isostore",                            "[urischemeowners_at_microsoft.com]"},
	{"itms",                                "itms",                                "[Dave_Thaler]"},
	{"jabber",                              "jabber",                              "[Peter_Saint-Andre]"},
	{"jar",                                 "jar",                                 "[Dave_Thaler]"},
	{"jms",                                 "Java Message Service",                "[RFC6167]"},
	{"keyparc",                             "keyparc",                             "[Dave_Thaler]"},
	{"lastfm",                              "lastfm",                              "[Dave_Thaler]"},
	{"ldap",                                "Lightweight Directory Access Proto",  "[RFC4516]"},
	{"ldaps",                               "ldaps",                               "[Dave_Thaler]"},
	{"leaptofrogans",                       "leaptofrogans",                       "[RFC8589]"},
	{"lorawan",                             "lorawan",                             "[OMA-DMSE]"},
	{"lvlt",                                "lvlt",                                "[Alexander_Shishenko]"},
	{"magnet",                              "magnet",                              "[Dave_Thaler]"},
	{"mailserver",                          "Access to data available from mail",  "[RFC6196]"},
	{"mailto",                              "Electronic mail address",             "[RFC6068]"},
	{"maps",                                "maps",                                "[Dave_Thaler]"},
	{"market",                              "market",                              "[Dave_Thaler]"},
	{"message",                             "message",                             "[Dave_Thaler]"},
	{"microsoft.windows.camera",            "microsoft.windows.camera",            "[urischemeowners_at_microsoft.com]"},
	{"microsoft.windows.camera.multipicker", "microsoft.windows.camera.multipick",  "[urischemeowners_at_microsoft.com]"},
	{"microsoft.windows.camera.picker",     "microsoft.windows.camera.picker",     "[urischemeowners_at_microsoft.com]"},
	{"mid",                                 "message identifier",                  "[RFC2392]"},
	{"mms",                                 "mms",                                 "[Alexey_Melnikov]"},
	{"modem",                               "modem",                               "[RFC2806][RFC3966]"},
	{"mongodb",                             "mongodb",                             "[Ignacio_Losiggio][Mongo_DB_Inc]"},
	{"moz",                                 "moz",                                 "[Joe_Hildebrand]"},
	{"ms-access",                           "ms-access",                           "[urischemeowners_at_microsoft.com]"},
	{"ms-browser-extension",                "ms-browser-extension",                "[urischemeowners_at_microsoft.com]"},
	{"ms-calculator",                       "ms-calculator",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-drive-to",                         "ms-drive-to",                         "[urischemeowners_at_microsoft.com]"},
	{"ms-enrollment",                       "ms-enrollment",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-excel",                            "ms-excel",                            "[urischemeowners_at_microsoft.com]"},
	{"ms-eyecontrolspeech",                 "ms-eyecontrolspeech",                 "[urischemeowners_at_microsoft.com]"},
	{"ms-gamebarservices",                  "ms-gamebarservices",                  "[urischemeowners_at_microsoft.com]"},
	{"ms-gamingoverlay",                    "ms-gamingoverlay",                    "[urischemeowners_at_microsoft.com]"},
	{"ms-getoffice",                        "ms-getoffice",                        "[urischemeowners_at_microsoft.com]"},
	{"ms-help",                             "ms-help",                             "[Alexey_Melnikov]"},
	{"ms-infopath",                         "ms-infopath",                         "[urischemeowners_at_microsoft.com]"},
	{"ms-inputapp",                         "ms-inputapp",                         "[urischemeowners_at_microsoft.com]"},
	{"ms-lockscreencomponent-config",       "ms-lockscreencomponent-config",       "[urischemeowners_at_microsoft.com]"},
	{"ms-media-stream-id",                  "ms-media-stream-id",                  "[urischemeowners_at_microsoft.com]"},
	{"ms-mixedrealitycapture",              "ms-mixedrealitycapture",              "[urischemeowners_at_microsoft.com]"},
	{"ms-mobileplans",                      "ms-mobileplans",                      "[urischemeowners_at_microsoft.com]"},
	{"ms-officeapp",                        "ms-officeapp",                        "[urischemeowners_at_microsoft.com]"},
	{"ms-people",                           "ms-people",                           "[urischemeowners_at_microsoft.com]"},
	{"ms-project",                          "ms-project",                          "[urischemeowners_at_microsoft.com]"},
	{"ms-powerpoint",                       "ms-powerpoint",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-publisher",                        "ms-publisher",                        "[urischemeowners_at_microsoft.com]"},
	{"ms-restoretabcompanion",              "ms-restoretabcompanion",              "[urischemeowners_at_microsoft.com]"},
	{"ms-screenclip",                       "ms-screenclip",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-screensketch",                     "ms-screensketch",                     "[urischemeowners_at_microsoft.com]"},
	{"ms-search",                           "ms-search",                           "[urischemeowners_at_microsoft.com]"},
	{"ms-search-repair",                    "ms-search-repair",                    "[urischemeowners_at_microsoft.com]"},
	{"ms-secondary-screen-controller",      "ms-secondary-screen-controller",      "[urischemeowners_at_microsoft.com]"},
	{"ms-secondary-screen-setup",           "ms-secondary-screen-setup",           "[urischemeowners_at_microsoft.com]"},
	{"ms-settings",                         "ms-settings",                         "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-airplanemode",            "ms-settings-airplanemode",            "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-bluetooth",               "ms-settings-bluetooth",               "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-camera",                  "ms-settings-camera",                  "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-cellular",                "ms-settings-cellular",                "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-cloudstorage",            "ms-settings-cloudstorage",            "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-connectabledevices",      "ms-settings-connectabledevices",      "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-displays-topology",       "ms-settings-displays-topology",       "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-emailandaccounts",        "ms-settings-emailandaccounts",        "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-language",                "ms-settings-language",                "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-location",                "ms-settings-location",                "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-lock",                    "ms-settings-lock",                    "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-nfctransactions",         "ms-settings-nfctransactions",         "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-notifications",           "ms-settings-notifications",           "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-power",                   "ms-settings-power",                   "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-privacy",                 "ms-settings-privacy",                 "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-proximity",               "ms-settings-proximity",               "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-screenrotation",          "ms-settings-screenrotation",          "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-wifi",                    "ms-settings-wifi",                    "[urischemeowners_at_microsoft.com]"},
	{"ms-settings-workplace",               "ms-settings-workplace",               "[urischemeowners_at_microsoft.com]"},
	{"ms-spd",                              "ms-spd",                              "[urischemeowners_at_microsoft.com]"},
	{"ms-sttoverlay",                       "ms-sttoverlay",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-transit-to",                       "ms-transit-to",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-useractivityset",                  "ms-useractivityset",                  "[urischemeowners_at_microsoft.com]"},
	{"ms-virtualtouchpad",                  "ms-virtualtouchpad",                  "[urischemeowners_at_microsoft.com]"},
	{"ms-visio",                            "ms-visio",                            "[urischemeowners_at_microsoft.com]"},
	{"ms-walk-to",                          "ms-walk-to",                          "[urischemeowners_at_microsoft.com]"},
	{"ms-whiteboard",                       "ms-whiteboard",                       "[urischemeowners_at_microsoft.com]"},
	{"ms-whiteboard-cmd",                   "ms-whiteboard-cmd",                   "[urischemeowners_at_microsoft.com]"},
	{"ms-word",                             "ms-word",                             "[urischemeowners_at_microsoft.com]"},
	{"msnim",                               "msnim",                               "[Alexey_Melnikov]"},
	{"msrp",                                "Message Session Relay Protocol",      "[RFC4975]"},
	{"msrps",                               "Message Session Relay Protocol Sec",  "[RFC4975]"},
	{"mss",                                 "mss",                                 "[Jarmo_Miettinen]"},
	{"mtqp",                                "Message Tracking Query Protocol",     "[RFC3887]"},
	{"mumble",                              "mumble",                              "[Dave_Thaler]"},
	{"mupdate",                             "Mailbox Update (MUPDATE) Protocol",   "[RFC3656]"},
	{"mvn",                                 "mvn",                                 "[Dave_Thaler]"},
	{"news",                                "USENET news",                         "[RFC5538]"},
	{"nfs",                                 "network file system protocol",        "[RFC2224]"},
	{"ni",                                  "ni",                                  "[RFC6920]"},
	{"nih",                                 "nih",                                 "[RFC6920]"},
	{"nntp",                                "USENET news using NNTP access",       "[RFC5538]"},
	{"notes",                               "notes",                               "[Dave_Thaler]"},
	{"ocf",                                 "ocf",                                 "[Dave_Thaler]"},
	{"oid",                                 "oid",                                 "[draft-larmouth-oid-iri]"},
	{"onenote",                             "onenote",                             "[urischemeowners_at_microsoft.com]"},
	{"onenote-cmd",                         "onenote-cmd",                         "[urischemeowners_at_microsoft.com]"},
	{"opaquelocktoken",                     "opaquelocktokent",                    "[RFC4918]"},
	{"openpgp4fpr",                         "openpgp4fpr",                         "[Wiktor_Kwapisiewicz]"},
	{"pack",                                "pack",                                "[draft-shur-pack-uri-scheme]"},
	{"palm",                                "palm",                                "[Dave_Thaler]"},
	{"paparazzi",                           "paparazzi",                           "[Dave_Thaler]"},
	{"payto",                               "payto",                               "[draft-dold-payto]"},
	{"pkcs11",                              "PKCS#11",                             "[RFC7512]"},
	{"platform",                            "platform",                            "[Dave_Thaler]"},
	{"pop",                                 "Post Office Protocol v3",             "[RFC2384]"},
	{"pres",                                "Presence",                            "[RFC3859]"},
	{"prospero",                            "Prospero Directory Service",          "[RFC4157]"},
	{"proxy",                               "proxy",                               "[Dave_Thaler]"},
	{"pwid",                                "pwid",                                "[Eld_Zierau]"},
	{"psyc",                                "psyc",                                "[Dave_Thaler]"},
	{"pttp",                                "pttp",                                "[Tony_Deng][Tuan_Hoang][Bob_Hinkle"},
	{"qb",                                  "qb",                                  "[Jan_Pokorny]"},
	{"query",                               "query",                               "[Dave_Thaler]"},
	{"redis",                               "redis",                               "[Chris_Rebert]"},
	{"rediss",                              "rediss",                              "[Chris_Rebert]"},
	{"reload",                              "reload",                              "[RFC6940]"},
	{"res",                                 "res",                                 "[Alexey_Melnikov]"},
	{"resource",                            "resource",                            "[Dave_Thaler]"},
	{"rmi",                                 "rmi",                                 "[Dave_Thaler]"},
	{"rsync",                               "rsync",                               "[RFC5781]"},
	{"rtmfp",                               "rtmfp",                               "[RFC7425]"},
	{"rtmp",                                "rtmp",                                "[Dave_Thaler]"},
	{"rtsp",                                "Real-Time Streaming Protocol (RTSP",  "[RFC2326][RFC7826]"},
	{"rtsps",                               "Real-Time Streaming Protocol (RTSP",  "[RFC2326][RFC7826]"},
	{"rtspu",                               "Real-Time Streaming Protocol (RTSP",  "[RFC2326]"},
	{"secondlife",                          "query",                               "[Dave_Thaler]"},
	{"service",                             "service location",                    "[RFC2609]"},
	{"session",                             "session",                             "[RFC6787]"},
	{"sftp",                                "query",                               "[Dave_Thaler]"},
	{"sgn",                                 "sgn",                                 "[Dave_Thaler]"},
	{"shttp",                               "Secure Hypertext Transfer Protocol",  "[RFC2660]"},
	{"sieve",                               "ManageSieve Protocol",                "[RFC5804]"},
	{"simpleledger",                        "simpleledger",                        "[James_Cramer]"},
	{"sip",                                 "session initiation protocol",         "[RFC3261]"},
	{"sips",                                "secure session initiation protocol",  "[RFC3261]"},
	{"skype",                               "skype",                               "[Alexey_Melnikov]"},
	{"smb",                                 "smb",                                 "[Dave_Thaler]"},
	{"sms",                                 "Short Message Service",               "[RFC5724]"},
	{"smtp",                                "smtp",                                "[draft-melnikov-smime-msa-to-mda]"},
	{"snews",                               "NNTP over SSL/TLS",                   "[RFC5538]"},
	{"snmp",                                "Simple Network Management Protocol",  "[RFC4088]"},
	{"soap.beep",                           "soap.beep",                           "[RFC4227]"},
	{"soap.beeps",                          "soap.beeps",                          "[RFC4227]"},
	{"soldat",                              "soldat",                              "[Dave_Thaler]"},
	{"spiffe",                              "spiffe",                              "[Evan_Gilman]"},
	{"spotify",                             "spotify",                             "[Dave_Thaler]"},
	{"ssh",                                 "ssh",                                 "[Dave_Thaler]"},
	{"steam",                               "steam",                               "[Dave_Thaler]"},
	{"stun",                                "stun",                                "[RFC7064]"},
	{"stuns",                               "stuns",                               "[RFC7064]"},
	{"submit",                              "submit",                              "[draft-melnikov-smime-msa-to-mda]"},
	{"svn",                                 "svn",                                 "[Dave_Thaler]"},
	{"tag",                                 "tag",                                 "[RFC4151]"},
	{"teamspeak",                           "teamspeak",                           "[Dave_Thaler]"},
	{"tel",                                 "telephone",                           "[RFC3966][RFC5341]"},
	{"teliaeid",                            "teliaeid",                            "[Peter_Lewandowski]"},
	{"telnet",                              "Reference to interactive sessions",   "[RFC4248]"},
	{"tftp",                                "Trivial File Transfer Protocol",      "[RFC3617]"},
	{"things",                              "things",                              "[Dave_Thaler]"},
	{"thismessage",                         "multipart/related relative referen",  "[RFC2557]"},
	{"tip",                                 "Transaction Internet Protocol",       "[RFC2371]"},
	{"tn3270",                              "Interactive 3270 emulation session",  "[RFC6270]"},
	{"tool",                                "tool",                                "[Matthias_Merkel]"},
	{"turn",                                "turn",                                "[RFC7065]"},
	{"turns",                               "turns",                               "[RFC7065]"},
	{"tv",                                  "TV Broadcasts",                       "[RFC2838]"},
	{"udp",                                 "udp",                                 "[Dave_Thaler]"},
	{"unreal",                              "unreal",                              "[Dave_Thaler]"},
	{"urn",                                 "Uniform Resource Names",              "[RFC8141][IANA registry urn-namesp"},
	{"ut2004",                              "ut2004",                              "[Dave_Thaler]"},
	{"v-event",                             "v-event",                             "[draft-menderico-v-event-uri]"},
	{"vemmi",                               "versatile multimedia interface",      "[RFC2122]"},
	{"ventrilo",                            "ventrilo",                            "[Dave_Thaler]"},
	{"videotex",                            "videotex",                            "[draft-mavrakis-videotex-url-spec]"},
	{"vnc",                                 "Remote Framebuffer Protocol",         "[RFC7869]"},
	{"view-source",                         "view-source",                         "[Mykyta_Yevstifeyev]"},
	{"wais",                                "Wide Area Information Servers",       "[RFC4156]"},
	{"webcal",                              "webcal",                              "[Dave_Thaler]"},
	{"wpid",                                "wpid",                                "[Eld_Zierau]"},
	{"ws",                                  "WebSocket connections",               "[RFC6455]"},
	{"wss",                                 "Encrypted WebSocket connections",     "[RFC6455]"},
	{"wtai",                                "wtai",                                "[Dave_Thaler]"},
	{"wyciwyg",                             "wyciwyg",                             "[Dave_Thaler]"},
	{"xcon",                                "xcon",                                "[RFC6501]"},
	{"xcon-userid",                         "xcon-userid",                         "[RFC6501]"},
	{"xfire",                               "xfire",                               "[Dave_Thaler]"},
	{"xmlrpc.beep",                         "xmlrpc.beep",                         "[RFC3529]"},
	{"xmlrpc.beeps",                        "xmlrpc.beeps",                        "[RFC3529]"},
	{"xmpp",                                "Extensible Messaging and Presence",   "[RFC5122]"},
	{"xri",                                 "xri",                                 "[Dave_Thaler]"},
	{"ymsgr",                               "ymsgr",                               "[Dave_Thaler]"},
	{"z39.50",                              "Z39.50 information access",           "[RFC1738][RFC2056]"},
	{"z39.50r",                             "Z39.50 Retrieval",                    "[RFC2056]"},
	{"z39.50s",                             "Z39.50 Session",                      "[RFC2056]"},
};

